import { Vinilo } from "../types/Vinilo";

const listaVinilos: Vinilo[] = [
  {
    id: 0,
    img: "/vinilos/covers/vinilo_amarillo.jpg",
    banda: "Lakes Of Materials",
    album: "Placebo Of Dust",
    albumImg: "placebo_of_dust.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 1,
    img: "/vinilos/covers/vinilo_azul.jpg",
    banda: "Fickle Atmosphere",
    album: "Flying Reality",
    albumImg: "flying_reality.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 2,
    img: "/vinilos/covers/vinilo_celeste.jpg",
    banda: "Rebel Gray",
    album: "House Black",
    albumImg: "house_black.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 3,
    img: "/vinilos/covers/vinilo_coral.jpg",
    banda: "Southwest Rome",
    album: "Anamorphic Dust",
    albumImg: "anamorphic_dust.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 4,
    img: "/vinilos/covers/vinilo_crema.jpg",
    banda: "Parandrus Anima",
    album: "Temper Games",
    albumImg: "temper_games.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 5,
    img: "/vinilos/covers/vinilo_morado.jpg",
    banda: "Torture Guts",
    album: "Drug",
    albumImg: "drug.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 6,
    img: "/vinilos/covers/vinilo_rojo.jpg",
    banda: "Southwest Orion",
    album: "Teeth For The Dead",
    albumImg: "teeth_for_the_dead.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 7,
    img: "/vinilos/covers/vinilo_verde.jpg",
    banda: "The Freedom",
    album: "A Religious Point",
    albumImg: "a_religious_point.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 8,
    img: "/vinilos/covers/vinilo_amarillo.jpg",
    banda: "Socrates",
    album: "Monastery Panic",
    albumImg: "monastery_panic.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 9,
    img: "/vinilos/covers/vinilo_azul.jpg",
    banda: "Godlike",
    album: "Lord Of Chernobyl",
    albumImg: "lord_of_chernobyl.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 10,
    img: "/vinilos/covers/vinilo_celeste.jpg",
    banda: "Pink Day",
    album: "Circular King",
    albumImg: "circular_king.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 11,
    img: "/vinilos/covers/vinilo_coral.jpg",
    banda: "The Burrowmail",
    album: "Un		der Biomes",
    albumImg: "under_biomes.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 12,
    img: "/vinilos/covers/vinilo_crema.jpg",
    banda: "Reflecting Covenant",
    album: "Platinum Of Silencing",
    albumImg: "platinum_of_silencing.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 13,
    img: "/vinilos/covers/vinilo_morado.jpg",
    banda: "Temper Orange",
    album: "Gravity Of You",
    albumImg: "gravity_of_you.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 14,
    img: "/vinilos/covers/vinilo_azul.jpg",
    banda: "Queen Purple",
    album: "Midnight",
    albumImg: "midnight.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 15,
    img: "/vinilos/covers/vinilo_verde.jpg",
    banda: "Speed Lavender",
    album: "Analogue Castle",
    albumImg: "analogue_castle.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 16,
    img: "/vinilos/covers/vinilo_amarillo.jpg",
    banda: "Deliberate Justice",
    album: "Before Rain",
    albumImg: "before_rain.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 17,
    img: "/vinilos/covers/vinilo_azul.jpg",
    banda: "The Actor",
    album: "Under Meteorites",
    albumImg: "under_meteorites.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 18,
    img: "/vinilos/covers/vinilo_celeste.jpg",
    banda: "Gray Cranium",
    album: "Losses",
    albumImg: "losses.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 19,
    img: "/vinilos/covers/vinilo_coral.jpg",
    banda: "The Southeast Photography",
    album: "Rolling",
    albumImg: "rolling.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 20,
    img: "/vinilos/covers/vinilo_crema.jpg",
    banda: "Orion Rome",
    album: "Whispering Atmosphere",
    albumImg: "whispering_atmosphere.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 21,
    img: "/vinilos/covers/vinilo_morado.jpg",
    banda: "Wyrmhut",
    album: "A Manifest Of Mistakes",
    albumImg: "a_manifest_of_mistakes.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 22,
    img: "/vinilos/covers/vinilo_rojo.jpg",
    banda: "Aeronautic",
    album: "The Sparkle",
    albumImg: "the_sparkle.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 23,
    img: "/vinilos/covers/vinilo_verde.jpg",
    banda: "Kings Of Wonders",
    album: "Wind Black",
    albumImg: "wind_black.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 24,
    img: "/vinilos/covers/vinilo_amarillo.jpg",
    banda: "Guard Lions",
    album: "Forged Pandemonium",
    albumImg: "forged_pandemonium.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 25,
    img: "/vinilos/covers/vinilo_azul.jpg",
    banda: "Daytime Gray",
    album: "Morphine",
    albumImg: "morphine.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 26,
    img: "/vinilos/covers/vinilo_celeste.jpg",
    banda: "Obsessed Talos",
    album: "Fathers",
    albumImg: "fathers.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 27,
    img: "/vinilos/covers/vinilo_coral.jpg",
    banda: "Grey Photo",
    album: "Finding Of Forests",
    albumImg: "finding_of_forest.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 28,
    img: "/vinilos/covers/vinilo_crema.jpg",
    banda: "Eternal",
    album: "Saving",
    albumImg: "saving.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 29,
    img: "/vinilos/covers/vinilo_morado.jpg",
    banda: "Freedoms Of Divers",
    album: "Realms",
    albumImg: "realms.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 30,
    img: "/vinilos/covers/vinilo_rojo.jpg",
    banda: "The Chestpeace",
    album: "Pausing Signs",
    albumImg: "pausing_signs.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 31,
    img: "/vinilos/covers/vinilo_verde.jpg",
    banda: "Road To Nowhere",
    album: "Return To Rome",
    albumImg: "return_to_rome.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 32,
    img: "/vinilos/covers/vinilo_amarillo.jpg",
    banda: "The Drunk Pillars",
    album: "The White Monkeys",
    albumImg: "the_white_monkeys.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 33,
    img: "/vinilos/covers/vinilo_azul.jpg",
    banda: "Molk",
    album: "Paying Of Your Jokers",
    albumImg: "paying_of_your_jokers.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 34,
    img: "/vinilos/covers/vinilo_celeste.jpg",
    banda: "Happy Eclipse",
    album: "Bubblegum",
    albumImg: "bubblegum.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 35,
    img: "/vinilos/covers/vinilo_coral.jpg",
    banda: "Organized Genova",
    album: "Juggernauts Of Pausing",
    albumImg: "juggernauts_of_pausing.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 36,
    img: "/vinilos/covers/vinilo_crema.jpg",
    banda: "O.R.I",
    album: "The Blackwell Sea",
    albumImg: "the_blackwell_sea.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 37,
    img: "/vinilos/covers/vinilo_morado.jpg",
    banda: "Journeys Of Feeling",
    album: "Velvet Sorcerers",
    albumImg: "velvet_sorcerers.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 38,
    img: "/vinilos/covers/vinilo_rojo.jpg",
    banda: "Pivotal Heart",
    album: "The Worshipping Of Your Songs",
    albumImg: "the_worshipping_of_your_songs.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 39,
    img: "/vinilos/covers/vinilo_verde.jpg",
    banda: "Fantasy Of Boys",
    album: "The Mirage",
    albumImg: "the_mirage.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 40,
    img: "/vinilos/covers/vinilo_amarillo.jpg",
    banda: "Epic Ships",
    album: "Loving Of Romance",
    albumImg: "loving_of_romance.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 41,
    img: "/vinilos/covers/vinilo_azul.jpg",
    banda: "European",
    album: "Materials",
    albumImg: "materials.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 42,
    img: "/vinilos/covers/vinilo_celeste.jpg",
    banda: "Cosmopolitan Savior",
    album: "Under Rainbows",
    albumImg: "under_rainbows.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 43,
    img: "/vinilos/covers/vinilo_coral.jpg",
    banda: "Anima Avalerion",
    album: "Kindled Noises",
    albumImg: "kindled_noises.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 44,
    img: "/vinilos/covers/vinilo_crema.jpg",
    banda: "The Crescent Doors",
    album: "Mothers",
    albumImg: "mothers.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 45,
    img: "/vinilos/covers/vinilo_morado.jpg",
    banda: "Golden",
    album: "The Spellbound Birds",
    albumImg: "the_spellbound_birds.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 46,
    img: "/vinilos/covers/vinilo_rojo.jpg",
    banda: "Summer Sleep",
    album: "Grown",
    albumImg: "grown.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 47,
    img: "/vinilos/covers/vinilo_verde.jpg",
    banda: "The Newshadow",
    album: "Perfect",
    albumImg: "perfect.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 48,
    img: "/vinilos/covers/vinilo_amarillo.jpg",
    banda: "The Wild Surgeons",
    album: "A Young Reckoning",
    albumImg: "a_young_reckoning.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 49,
    img: "/vinilos/covers/vinilo_azul.jpg",
    banda: "Drawbeetle",
    album: "Warden White",
    albumImg: "warden_white.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 50,
    img: "/vinilos/covers/vinilo_celeste.jpg",
    banda: "Moontear",
    album: "Screaming For Rome",
    albumImg: "screaming_for_rome.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 51,
    img: "/vinilos/covers/vinilo_coral.jpg",
    banda: "Supreme Covenants",
    album: "A Saving Text",
    albumImg: "a_saving_text.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 52,
    img: "/vinilos/covers/vinilo_crema.jpg",
    banda: "Evil Genova",
    album: "Under Vampires",
    albumImg: "under_vampires.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 53,
    img: "/vinilos/covers/vinilo_morado.jpg",
    banda: "Genova Carnage",
    album: "After Police",
    albumImg: "after_police.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 54,
    img: "/vinilos/covers/vinilo_rojo.jpg",
    banda: "Atmosphere",
    album: "Ash Yellow",
    albumImg: "ash_yellow.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
  {
    id: 55,
    img: "./images/vinilos/covers/vinilo_verde.jpg",
    banda: "Innocent Utopia",
    album: "Molten Lords",
    albumImg: "molten_lords.png",
    galeria: ["", "", ""],
    genero: "",
    anio: 0,
    precio: 0,
    stock: 0,
    cantidad: 1,
    vendidos: 0,
    puntuacion: [],
  },
];

function randomNumber(min = 0, max = 0) {
  return Math.round(Math.random() * (max - min) + min);
}
listaVinilos.forEach((v, i) => {
  v.id = i;
  v.anio = randomNumber(1970, 2022);
  v.precio = randomNumber(20, 150);
  v.stock = randomNumber(1, 30);
  const times = randomNumber(1, 20);
  for (let i = 0; i < times; i++) {
    v.puntuacion.push(randomNumber(0, 5));
  }
});
export default listaVinilos;
